### ISSUE TITLE
Problems with inlined type constraints

### ISSUE THREAD

**Issue by tobyink** [robrwo/Net-Statsd-Lite#1]
The PosInt type, for example, is defined this way:

```
declare "PosInt", as Int,
  where { $_ >= 0 },
  inline_as { my $n = $_[1]; "$n >= 0" };
```

However, `inline_as` blocks are expected to also check the value validates against the parent constraint. So your check is just comparing `$n` against 0. It's not checking that `$n` is an integer.

```
perl -MNet::Statsd::Lite::Types=PosInt -E'say PosInt->compiled_check->(1.1)'
```

The above prints `1` (true). So the value 1.1 is accepted as a positive integer, because you're not checking the value is an integer.

This feature of the inlining API is inherited from Moose, which Type::Tiny aims to mimic. And it does make sense if you want to build very efficient inlined type checks. `HashRef` inherits from `Ref` which inherits from `Defined`. So you could end up with checks like:

    defined($val) and ref($val) and ref($val) eq 'HASH'

If the `inline_as` block can short-circuit the parent checks, we can short-circuit checking definedness and checking ref twice, and it can be inlined as just:

    ref($val) eq 'HASH'.

But in your case, you don't want `PosInt` to short-circuit the `Int` check. So:

```
declare "PosInt", as Int,
  where { $_ >= 0 },
  inline_as { my $n = $_[1]; sprintf("%s and %s >= 0", Int->inline_check($n), $n) };
```

Because this is a pretty common pattern, there's a shortcut for it. If you return a list, they are joined together with `and`, and if the first item on that list is `undef`, the parent type check will be used.

```
declare "PosInt", as Int,
  where { $_ >= 0 },
  inline_as { my $n = $_[1]; (undef, "$n >= 0") };
```

**Comment by robrwo** [comment]
@tobyink Thanks, I'll take a look at that.

**Comment by kwakwaversal** [comment]
@tobyink your suggested pattern is still marked as [experimental](https://metacpan.org/pod/Type::Utils#inline_as-{-BLOCK-}) in the documentation, is this still the case?

**Comment by tobyink** [comment]
I can't see it changing unless Moose does something that would break it. (Unlikely.)
